Set AWS_S3_MAX_MEMORY_SIZE
cookiecutter/cookiecutter-django pull request #3810
Opened 2022-07-26 17:58 UTC by danihodovic

> The maximum amount of memory (in bytes) a file can take up before being
> rolled over into a temporary file on disk.

Prevents out of memory eviction when a large file is uploaded.

2022-07-26 23:15 UTC, browniebroke approved these changes

2022-07-27 12:47 UTC, luzfcb requested changes

2022-07-27 12:47 UTC, luzfcb commented on {{cookiecutter.project_slug}}/config/settings/production.py
> +AWS_S3_MAX_MEMORY_SIZE = env.int("AWS_S3_MAX_MEMORY_SIZE", default=100_000_000)  # 100MB
To follow our standard, it probably needs to change to `DJANGO_AWS_S3_MAX_MEMORY_SIZE` and also update the settings table in the docs: https://github.com/cookiecutter/cookiecutter-django/blob/master/docs/settings.rst

```suggestion
AWS_S3_MAX_MEMORY_SIZE = env.int("DJANGO_AWS_S3_MAX_MEMORY_SIZE", default=100_000_000)  # 100MB
```

2022-08-21 14:55 UTC, danihodovic commented
Amended fixes. Would you like me to rebase and squash?

2022-08-24 21:44 UTC, browniebroke commented on {{cookiecutter.project_slug}}/config/settings/production.py
> +AWS_S3_MAX_MEMORY_SIZE = env.int("DJANGO_AWS_S3_MAX_MEMORY_SIZE", default=100_000_000)  # 100MB
```suggestion
AWS_S3_MAX_MEMORY_SIZE = env.int(
    "DJANGO_AWS_S3_MAX_MEMORY_SIZE", 
    default=100_000_000,    # 100MB
)
```

2022-08-24 21:44 UTC, browniebroke commented on {{cookiecutter.project_slug}}/config/settings/production.py
> +    default=100_000_000,    # 100MB
```suggestion
    default=100_000_000,  # 100MB
```

2022-08-24 21:49 UTC, browniebroke commented on {{cookiecutter.project_slug}}/config/settings/production.py
> +    "DJANGO_AWS_S3_MAX_MEMORY_SIZE",
```suggestion
    "DJANGO_AWS_S3_MAX_MEMORY_SIZE",
```

2022-08-24 21:59 UTC, browniebroke approved these changes
I think that's good to go now @luzfcb?

2022-09-26 13:46 UTC, danihodovic commented
Ping @luzfcb

2022-10-19 19:15 UTC, merged

2022-10-19 19:15 UTC, browniebroke commented
I'm going to go ahead and assume that it's fine. If not, we can always revert this. Thanks for the contribution @danihodovic!