Change psycopg2 to psycopg3
cookiecutter/cookiecutter-django pull request #4421
Opened 2023-06-27 20:39 UTC by Andrew-Chen-Wang

## Description

Change psycopg2 to psycopg3. Ready once #4393 is merged.

Checklist:

- [ ] I've made sure that tests are updated accordingly (especially if adding or updating a template option)
- [ ] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

Django 4.2 adds support for the latest, faster psycopg(3)

2023-06-28 07:06 UTC, foarsitter requested changes
The actions fail because you missed this line:
https://github.com/cookiecutter/cookiecutter-django/blob/6f34e19260f9909752277f81f3282ff6fba4a584/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/entrypoint#L23

2023-06-28 13:26 UTC, Andrew-Chen-Wang commented
thanks; ready @browniebroke @foarsitter

2023-06-28 22:34 UTC, browniebroke approved these changes
I would have expected a bigger change, nice!

2023-06-29 06:58 UTC, foarsitter approved these changes

2023-06-29 06:58 UTC, merged