Update testing.rst - coverage config file is now pyproject.toml
cookiecutter/cookiecutter-django pull request #4816
Opened 2024-01-28 19:48 UTC by henningbra

## Description

Checklist:

- [ ] I've made sure that tests are updated accordingly (especially if adding or updating a template option)
- [x] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

2024-01-28 20:38 UTC, foarsitter requested changes
In my opinion your change is to briefly. It is that project.toml is the location where it is configured but the file is not dedicated to coverage.

2024-01-28 20:49 UTC, henningbra commented
I'm new to contributing - learning. Just wanted to contribute to point out an error in the docs. Feel free to close it :-)

Allauth is a fantastic package for our Human Elephant Conflict mitigation system in a non profit organization.

2024-01-29 09:23 UTC, foarsitter commented
Your contribution if more then welkom @henningbra! 

I would suggest something like this: 

```
The configuration for ``coverage`` can be found in `pyproject.toml`. You can find out more about `configuring`_ ``coverage``.
```

2024-01-29 13:01 UTC, browniebroke commented on docs/testing.rst
> +   There is also the `pyproject.toml`. This is the configuration file for the ``coverage`` tool. You can find out more about `configuring`_ ``coverage``.
```suggestion
   The configuration for ``coverage`` can be found in ``pyproject.toml``. You can find out more about `configuring`_ ``coverage``.
```

2024-01-29 13:02 UTC, browniebroke approved these changes
Thanks for the fix and good point @foarsitter, I've applied your suggestion.

2024-01-29 13:04 UTC, foarsitter approved these changes

2024-01-29 13:09 UTC, merged

2024-01-29 16:59 UTC, henningbra commented
I'm new. After the merge should I delete branch?

2024-01-29 17:18 UTC, foarsitter commented
Yes, I should delete it or even delete the hole fork.