Use uv sync & uv run in docs build
cookiecutter/cookiecutter-django pull request #5440
Opened 2024-10-07 19:26 UTC by browniebroke

## Description

The offical RTD guide was written a few months ago and I realised after merging https://github.com/cookiecutter/cookiecutter-django/pull/5438 that we can in fact simplify a bit more.

Also upstreamed these changes to RTD: https://github.com/readthedocs/readthedocs.org/pull/11655

Checklist:

- [ ] I've made sure that tests are updated accordingly (especially if adding or updating a template option)
- [ ] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

Simpler build steps

2024-10-07 20:13 UTC, foarsitter requested changes
This was the flow I expected in the first place but didn't know how to install the optional dependencies and the existence of --extras. 

I would expect the --no-dev and --frozen parameters here. Dev requirements are not required and the lock file should not change.

2024-10-07 20:43 UTC, browniebroke commented
> I would expect the --no-dev and --frozen parameters here

Good point! Fixed

2024-10-08 05:52 UTC, foarsitter approved these changes

2024-10-08 05:53 UTC, foarsitter commented
Forgot that we don't have dev dependencies xD 

Will add some soon ;)

2024-10-08 05:54 UTC, merged